export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const PRODUCT_ROUTE = '/product'
export const SHOPS_ROUTE = '/shops'